// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package internal

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Index() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html><script src=\"https://unpkg.com/htmx.org@1.9.10\"></script><style type=\"text/css\">\n\t\t\t.textarea {\n\t\t\t\twidth: 99%;\n\t\t\t\theight: 100%; \n\t\t\t\tresize: none;\n\t\t\t\tmargin-right: 10px;\n\t\t\t}\n\t\t\t\n\t\t\tinput {\n\t\t\t\tmargin-bottom: 10px;\n\t\t\t}\n\t\t</style><div class=\"\"><form hx-post=\"/upload/paste\" hx-swap=\"none\"><input type=\"submit\" value=\"Paste\"> <textarea placeholder=\"Your content goes here\" name=\"content\" class=\"textarea\" spellcheck=\"false\" oninput=\"autoResize(this)\"></textarea></form></div><script>\n\t\t\thtmx.on(\"htmx:afterRequest\", function (evt) {\n\t\t\t\tif (evt.detail.successful) {\n\t\t\t\t\twindow.location.href = \"/\" + evt.detail.xhr.response\n\t\t\t\t}\n\t\t\t});\n\n\t\t\tfunction autoResize(textarea) {\n\t\t\t    textarea.style.height = \"auto\";\n\t\t\t    textarea.style.height = textarea.scrollHeight + \"px\";\n\t\t\t}\n\t\t</script></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func Paste(paste string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html><style>\n\t\t\t.paste-div {\n\t\t\t}\n\n\t\t\thtml {\n\t\t\t\tbackground-color: white;\n\t\t\t}\n\t\t</style><div class=\"paste-div\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(paste).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
